application:
  service:
    url:
      white: login,swagger,error
jwt:
  token:
    sig: helloworld
#server:
#  servlet:
#    context-path: /api


logging:
  level: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl